export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'

export const AUTH_STATUS_SUCCESS = 'AUTH_STATUS_SUCCESS'
export const AUTH_STATUS_FAILED = 'AUTH_STATUS_FAIL'

export const LOG_OUT = 'LOG_OUT'

export const CONNEXION_SUCCESS = 'CONNEXION_SUCCESS'
export const CONNEXION_FAIL = 'CONNEXION_FAIL'
export const LIST_NO_INIT_ROOT = 'LIST_NO_INIT_ROOT'
export const LIST_INIT_ROOT = 'LIST_INIT_ROOT'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const MOVE_SUCCESS = 'MOVE_SUCCESS'

export const FTP_CREDENTIALS = 'FTP_CREDENTIALS'

